{
  fetchFromGitHub,
  lib,
  python312Packages,
}:
python312Packages.buildPythonApplication rec {
  pname = "asm-differ";
  version = "0.1.0-unstable-2026-09-06";
  pyproject = true;

  src = fetchFromGitHub {
    owner = "simonlindholm";
    repo = "asm-differ";
    rev = "0dd09af8f8008f1f880327cf0aca3b26d2562ea2";
    hash = "sha256-CnEwuJuHNRAcE200nLJXulLUqYtnq+htH9iSzsHRgAI=";
  };

  patches = [ ./asm-differ-help-without-config.patch ];

  build-system = [ python312Packages.poetry-core ];

  dependencies = with python312Packages; [
    colorama
    cxxfilt
    levenshtein
    watchdog
  ];

  doCheck = true;
  checkPhase = ''
    runHook preCheck
    python -m unittest -v test.py

    export HOME="$TMPDIR"
    cd "$TMPDIR"
    $out/bin/asm-differ --help | grep -F "Diff MIPS"

    smoke="$TMPDIR/asm-differ-smoke"
    mkdir -p "$smoke"
    cd "$smoke"

    cat > diff_settings.py <<'PY'
    def apply(config, args):
        config["arch"] = "mips"
        config["baseimg"] = "base.bin"
        config["myimg"] = "current.bin"
        config["objdump_executable"] = "./fake-objdump"
    PY

    touch base.bin current.bin
    cat > fake-objdump <<'SH'
    #!/bin/sh
    cat <<'ASM'
    smoke.bin: file format binary


    Disassembly of section .data:


    00000000 <smoke>:
       0:	24020001 	addiu	v0,zero,1
       4:	03e00008 	jr	ra
       8:	00000000 	nop
    ASM
    SH
    chmod +x fake-objdump

    $out/bin/asm-differ 0 --format=json > diff.json
    grep -F '"arch_str": "mips"' diff.json
    grep -F 'addiu' diff.json

    runHook postCheck
  '';
  pythonImportsCheck = [ "diff" ];

  meta = {
    description = "Diff tool for assembly generated by matching decompilation projects";
    homepage = "https://github.com/simonlindholm/asm-differ";
    license = lib.licenses.unlicense;
    mainProgram = "asm-differ";
    platforms = lib.platforms.unix;
  };
}
